### PR TITLE
Add LogLevel support to Tasks and ExternalProcesses.

### PR DESCRIPTION
**Pull request by albyrock87**
Add LogLevel support to Tasks and ExternalProcesses.

### CODE REVIEW

**Comment by mzorec** [comment]
This feature sounds reasonoble to me. 

Among your suggestions I like `bool logErrorOutputOnly = false:` the most. Maybe `bool logOnlyErrors = false:` would be better as Output is already in the method name ' DoNotLogOutput'.

I am also thinking that we could obsolete  ' DoNotLogOutput '  and add  ' OutputLogLevel(LogLevel logLevel) 

LogLevel enum could be: 

- Info
- Error
- None

What do you think about this alternative?

**Comment by albyrock87** [comment]
I like it: LogLevel sounds natural.
I'll do it and get back to you.

**Comment by albyrock87** [comment]
Hi @mzorec ,
I've just pushed `LogLevel` changes we've talked about, let me know if it looks good to you.

**Comment by mzorec** [comment]
Looks good. I am only not sure about the naming.

`WithProcessLogLevel` in my opinion it should be `WithOutputLogLevel` or `WithProcessOutputLogLevel` as we are logging output of the process and not setting the log level of the process itself. I've looked at microsoft library that FlubuCore uses and they also use Output in similar cases.

 I am also not sure if we really need `With` in any case.

**Comment by albyrock87** [comment]
I just changed `ProcessLogLevel` to `OutputLogLevel`.

The problemi with `With` is that if I call a method `LogLevel` (inside `TaskBase`) it would conflict with the `enum LogLevel`.

I also don't like `With` keyword but I don't have a better solution atm.

**Comment by mzorec** [comment]
Build looks ok.. probablly some flacky test. 

Thank you for PR!

**Comment by mzorec** [comment]
Released in 6.1.0

**Pull request merged**
