### PR TITLE
 Store json configuration file path to .flubu file 

### LINKED ISSUE #261: Store json configuration file path to .flubu file
Would it be possible that json configuration file path is stored in .flubu file? This would solve that path to the file wouldn't needed to be passed through `-cf `option every time when it is different than flubusettings.json

### PR DESCRIPTION
**Pull request by SixGoesNine**
Fixes #261

### CODE REVIEW

**Comment by SixGoesNine** [comment]
I am having an issue completing this PR. I've changed FlubuCommandParser so it accepts IBuildScriptLocator because I need to find flubu file in FlubuCommandParser. Issue is I don't know how to initialize properly FlubuCommandParser now in InstallerExtensions. Easiest way imo would be if you would clone my fork and take a look and give me some directions how to solve this issue.

**Comment by mzorec** [comment]
I've took a look and if you don't mind I would fix this myself on your fork. It would be alot faster and easier than explaining all the details to you.

**Comment by SixGoesNine** [comment]
Sure :)

**Comment by mzorec** [comment]
I've resolved issue with initialization of FlubuComandParser.

**Pull request merged**
